{% set data = load_setup_py_data() %}

package:
  name: "pymt_prms_soil"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - prms 
    - prms_soil 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - prms 
    - prms_soil 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_prms_soil
  commands:
    - config_file=$(mmd-stage PRMSSoil . > MANIFEST && mmd-query PRMSSoil --var=run.config_file.path)
    - bmi-test pymt_prms_soil.bmi:PRMSSoil --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the prms_soil BMI.
  home: https://github.com/pymt-lab/pymt_prms_soil
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_prms_soil
